version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speech-translator-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./service-account.json:/app/service-account.json:ro
    restart: unless-stopped
